# Veganism
- arguer: vegan
  raters:
  - VEGAN
  - Non_vegan
  path:
  - creating_materials/vegan_vegan_RATINGS
  - creating_materials/VArgs_NvRatings

- arguer: nonVegan
  raters:
  - Vegan
  - NONvegan
  path:
  - creating_materials/NvArgs_VRatings
  - creating_materials/Nv_Nv_RATINGS

# Brexit
- arguer: leave
  raters:
  - LEAVE
  - REMAIN
  path:
  - creating_materials/Lev_Lev_RATINGS
  - creating_materials/Lev_Rem_RATINGS

- arguer: remain
  raters:
  - LEAVE
  - REMAIN
  path:
  - creating_materials/Rem_Lev_RATINGS
  - creating_materials/RemRemRatings

# Vaccines
- arguer: hes
  raters:
  - Hesitant
  - Pro
  path:
  - creating_materials/HesHesRatings
  - creating_materials/HesProRatings

- arguer: pro
  raters:
  - Hesitant
  - Pro
  path:
  - creating_materials/ProHesRatings
  - creating_materials/ProProRatings
  
