model_names:
- "brexit_intellect"
- "brexit_morality"
- "vegan_morality_abs"
- "vegan_intellect_rel"
- "vegan_morality_rel"
- "vegan_stanley_rel"


plot_config:
  file_output:
    width: 8
    height: 5
    units: "in"
    dpi: "print"
